M48
; DRILL file {KiCad 9.0.2} date 2025-09-10T14:09:24+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-10T14:09:24+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X148.91Y-123.985
X154.69Y-123.985
T2
X114.0Y-124.9
X114.2Y-66.2
X192.7Y-66.0
X192.9Y-124.7
M30
